"use client";

import { useState } from "react";
import ReactMarkdown from "react-markdown";

interface Step {
  tool: string;
  detail: string;
}

export default function Home() {
  const [company, setCompany] = useState("");
  const [steps, setSteps] = useState<Step[]>([]);
  const [report, setReport] = useState("");
  const [loading, setLoading] = useState(false);

  async function research() {
    if (!company.trim()) return;
    setSteps([]);
    setReport("");
    setLoading(true);

    try {
      const response = await fetch(
        `${process.env.NEXT_PUBLIC_API_URL}/research`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ company }),
        }
      );

      const reader = response.body!.getReader();
      const decoder = new TextDecoder();
      let buffer = "";

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split("\n");
        buffer = lines.pop() || "";

        for (const line of lines) {
          if (!line.startsWith("data: ")) continue;
          const data = JSON.parse(line.slice(6));

          if (data.type === "step") {
            setSteps((prev) => [...prev, { tool: data.tool, detail: data.detail }]);
          } else if (data.type === "report") {
            setReport(data.content);
          } else if (data.type === "done") {
            setLoading(false);
          }
        }
      }
    } catch (err) {
      setSteps((prev) => [...prev, { tool: "error", detail: String(err) }]);
    } finally {
      setLoading(false);
    }
  }

  async function downloadPDF() {
    const { default: jsPDF } = await import("jspdf");
    const doc = new jsPDF();

    // Title
    doc.setFontSize(20);
    doc.setTextColor(13, 31, 66);
    doc.text(`${company} — Research Brief`, 20, 25);

    // Subtitle
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by AI Research Agent · ${new Date().toLocaleDateString()}`, 20, 33);

    // Red divider line
    doc.setDrawColor(232, 51, 58);
    doc.setLineWidth(0.8);
    doc.line(20, 38, 190, 38);

    // Report content
    doc.setFontSize(11);
    doc.setTextColor(55, 65, 81);
    const lines = doc.splitTextToSize(report, 170);
    let y = 46;
    const pageHeight = 280;

    for (const line of lines) {
      if (y > pageHeight) {
        doc.addPage();
        y = 20;
      }
      // Style headings
      if (line.startsWith("##")) {
        doc.setFontSize(14);
        doc.setTextColor(13, 31, 66);
        doc.setFont("helvetica", "bold");
        doc.text(line.replace(/^#+\s*/, ""), 20, y);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);
        doc.setTextColor(55, 65, 81);
        y += 8;
      } else if (line.startsWith("#")) {
        doc.setFontSize(12);
        doc.setTextColor(13, 31, 66);
        doc.setFont("helvetica", "bold");
        doc.text(line.replace(/^#+\s*/, ""), 20, y);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);
        doc.setTextColor(55, 65, 81);
        y += 7;
      } else {
        doc.text(line, 20, y);
        y += 6;
      }
    }

    doc.save(`${company.toLowerCase().replace(/\s+/g, "-")}-research.pdf`);
  }

  function handleKey(e: React.KeyboardEvent) {
    if (e.key === "Enter" && !loading && company.trim()) research();
  }

  const hasContent = steps.length > 0 || report;

  return (
    <>
      {/* Header */}
      <header className="header">
        <div className="header-inner">
          <div className="logo">
            Research<span>AI</span>
          </div>
          <div className="header-tag">Powered by Claude</div>
        </div>
      </header>

      {/* Hero / Search */}
      <div className="hero">
        <h1>Research any company in 60 seconds</h1>
        <p>AI agent that searches the web, reads real pages, and writes a full research brief</p>
        <div className="search-row">
          <input
            className="search-input"
            value={company}
            onChange={(e) => setCompany(e.target.value)}
            onKeyDown={handleKey}
            placeholder="e.g. Stripe, Anthropic, Linear..."
            disabled={loading}
          />
          <button
            className="search-btn"
            onClick={research}
            disabled={loading || !company.trim()}
          >
            {loading ? "Researching..." : "Research →"}
          </button>
        </div>
      </div>

      {/* Content grid */}
      {hasContent && (
        <div className="container">
          <div className="grid">

            {/* Left — Activity feed */}
            <div className="card">
              <div className="card-header">
                <span className="card-title">Live Activity</span>
                {loading && <span style={{ fontSize: 11, color: "#f59e0b", fontWeight: 600 }}>Running...</span>}
              </div>
              <div className="activity-list">
                {steps.map((step, i) => (
                  <div className="activity-item" key={i}>
                    <div className="activity-dot" />
                    <div>
                      <div className="activity-tool">{step.tool}</div>
                      <div className="activity-detail">{step.detail}</div>
                    </div>
                  </div>
                ))}
                {loading && (
                  <div className="activity-item">
                    <div className="activity-dot pulse" />
                    <div>
                      <div className="activity-tool">thinking</div>
                      <div className="activity-detail">agent is deciding next step...</div>
                    </div>
                  </div>
                )}
                {!loading && steps.length === 0 && (
                  <div className="empty-state">
                    <div className="empty-icon">⚡</div>
                    <p>Steps will appear here</p>
                  </div>
                )}
              </div>
            </div>

            {/* Right — Report */}
            <div className="card">
              <div className="card-header">
                <span className="card-title">Research Report</span>
                {report && (
                  <div className="report-actions">
                    <button className="download-btn" onClick={downloadPDF}>
                      ⬇ Download PDF
                    </button>
                  </div>
                )}
              </div>

              {report ? (
                <div className="report-body">
                  <ReactMarkdown>{report}</ReactMarkdown>
                </div>
              ) : (
                <div className="empty-state">
                  <div className="empty-icon">📋</div>
                  <p>Your research report will appear here</p>
                </div>
              )}
            </div>

          </div>
        </div>
      )}
    </>
  );
}
